In [19]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [20]:
pumpkins = pd.read_csv('US_pumpkins.csv')
pumpkins.head()

,City Name,Type,Package,Variety,Sub Variety,Grade,Date,Low Price,High Price,Mostly Low,...,Unit of Sale,Quality,Condition,Appearance,Storage,Crop,Repack,Trans Mode,Unnamed: 24,Unnamed: 25
0,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,4/29/17,270.0,280.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,NaN,NaN
1,BALTIMORE,NaN,24 inch bins,NaN,NaN,NaN,5/6/17,270.0,280.0,270.0,...,NaN,NaN,NaN,NaN,NaN,NaN,E,NaN,NaN,NaN
2,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,9/24/16,160.0,160.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
3,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,9/24/16,160.0,160.0,160.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN
4,BALTIMORE,NaN,24 inch bins,HOWDEN TYPE,NaN,NaN,11/5/16,90.0,100.0,90.0,...,NaN,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN

In [21]:
pumpkins.isnull().sum()

City Name             0
Type               1712
Package               0
Variety               5
Sub Variety        1461
Grade              1757
Date                  0
Low Price             0
High Price            0
Mostly Low          103
Mostly High         103
Origin                3
Origin District    1626
Item Size           279
Color               616
Environment        1757
Unit of Sale       1595
Quality            1757
Condition          1757
Appearance         1757
Storage            1757
Crop               1757
Repack                0
Trans Mode         1757
Unnamed: 24        1757
Unnamed: 25        1654
dtype: int64

In [22]:
df = {
    'City Name' : pumpkins['City Name'],
    'Package' : pumpkins['Package'],
    'Variety' : pumpkins['Variety'],
    'Low Price' : pumpkins['Low Price'],
    'High Price' : pumpkins['High Price'],
    'Date' : pumpkins['Date'],
    'Color' : pumpkins['Color'],
    'Origin' : pumpkins['Origin'],
    'Item Size' : pumpkins['Item Size'],
    'Repack' : pumpkins['Repack']
}
new_pumpkins = pd.DataFrame(df)
new_pumpkins

,City Name,Package,Variety,Low Price,High Price,Date,Color,Origin,Item Size,Repack
0,BALTIMORE,24 inch bins,NaN,270.00,280.00,4/29/17,NaN,MARYLAND,lge,E
1,BALTIMORE,24 inch bins,NaN,270.00,280.00,5/6/17,NaN,MARYLAND,lge,E
2,BALTIMORE,24 inch bins,HOWDEN TYPE,160.00,160.00,9/24/16,ORANGE,DELAWARE,med,N
3,BALTIMORE,24 inch bins,HOWDEN TYPE,160.00,160.00,9/24/16,ORANGE,VIRGINIA,med,N
4,BALTIMORE,24 inch bins,HOWDEN TYPE,90.00,100.00,11/5/16,ORANGE,MARYLAND,lge,N
...,...,...,...,...,...,...,...,...,...,...
1752,ST. LOUIS,22 lb cartons,MINIATURE,14.75,14.75,9/30/16,WHITE,ILLINOIS,NaN,N
1753,ST. LOUIS,36 inch bins,MINIATURE,275.00,275.00,9/26/16,NaN,MICHIGAN,sml,N
1754,ST. LOUIS,36 inch bins,MINIATURE,275.00,275.00,9/27/16,NaN,MICHIGAN,sml,N
1755,ST. LOUIS,36 inch bins,MINIATURE,275.00,275.00,9/28/16,NaN,MICHIGAN,sml,N
1756,ST. LOUIS,36 inch bins,MINIATURE,275.00,275.00,9/29/16,NaN,MICHIGAN,sml,N

In [23]:
new_pumpkins = new_pumpkins.apply(LabelEncoder().fit_transform)
new_pumpkins.info

<bound method DataFrame.info of       City Name  Package  Variety  Low Price  High Price  Date  Color  Origin  \
0             1        5       10         82          78    27      3       8
1             1        5       10         82          78    32      3       8
2             1        5        4         63          58    49      0       4
3             1        5        4         63          58    49      0      22
4             1        5        4         46          46    13      0       8
...         ...      ...      ...        ...         ...   ...    ...     ...
1752         12        4        7          9           9    54      2       6
1753         12        7        7         83          77    50      3      11
1754         12        7        7         83          77    51      3      11
1755         12        7        7         83          77    52      3      11
1756         12        7        7         83          77    53      3      11

      Item Size  Repack
0             2       0
1             2       0
2             3       1
3             3       1
4             2       1
...         ...     ...
1752          7       1
1753          5       1
1754          5       1
1755          5       1
1756          5       1

[1757 rows x 10 columns]>

In [39]:
from sklearn.model_selection import train_test_split

features = ['City Name', 'Package', 'Variety', 'Low Price', 'High Price', 'Date', 'Origin', 'Item Size', 'Repack']
target = 'Color'

X = new_pumpkins[features]
y = new_pumpkins[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.23, random_state=0)

In [50]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000, solver='sag', penalty='l2')
model.fit(X_train, y_train)
prediction = model.predict(X_test)

/home/khalboy10/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

In [51]:
from sklearn.metrics import accuracy_score, classification_report

print(classification_report(y_test, prediction))
print('Predicted labels: ', prediction)
print('Accuracy: ', accuracy_score(y_test, prediction))

              precision    recall  f1-score   support

           0       0.62      0.85      0.72       215
           1       0.00      0.00      0.00         3
           2       0.18      0.08      0.11        38
           3       0.59      0.38      0.46       149

    accuracy                           0.60       405
   macro avg       0.35      0.33      0.32       405
weighted avg       0.56      0.60      0.56       405

Predicted labels:  [0 3 0 0 0 0 3 0 3 3 0 0 3 0 0 0 0 0 0 0 0 0 0 3 0 3 3 0 0 2 0 3 0 0 0 0 0
 0 0 0 0 3 0 0 3 0 0 3 2 0 0 0 3 3 0 3 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0
 0 0 3 0 0 0 3 0 0 0 0 0 0 0 3 0 0 3 0 0 3 0 3 0 2 0 0 0 3 0 3 0 0 0 0 3 0
 0 0 0 0 0 0 3 0 0 3 3 2 3 0 0 0 0 0 0 0 3 0 0 0 0 3 0 3 0 0 3 0 0 3 0 0 0
 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 3 0 3 0 0 0 0 0 3 0 0 0 3 0 0 0 0 0
 0 0 0 0 0 0 0 0 2 2 0 0 2 0 0 0 0 3 3 0 0 0 0 3 3 0 0 3 0 3 0 0 0 2 3 0 3
 0 0 0 0 3 0 0 0 0 0 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 2 0 3 3 3 0 3 3
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 0 0 3 0 2 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3
 3 0 0 3 3 0 3 3 3 3 3 0 3 0 3 3 3 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 3 0 3 3
 3 0 0 0 0 0 0 0 2 2 0 0 0 3 0 0 3 0 0 2 0 0 0 0 0 0 2 0 0 0 2 0 3 0 0 3 0
 0 0 0 0 0 3 0 3 3 0 0 0 0 0 3 0 0 3 0 0 2 0 2 0 3 0 3 0 0 3 0 0 0 3 3]
Accuracy:  0.5950617283950618

/home/khalboy10/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/khalboy10/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/khalboy10/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))